language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - composer self-update
    - composer install --prefer-source --no-interaction

script:
    - bin/phpspec run